name: Exécution Installation des modules
on: workflow_dispatch
jobs:
  InstallationModulesJob:
    runs-on: ubuntu-latest
    steps:
      - name: Activation lecture du repo
        uses: actions/checkout@v4
      - name: Installation effective
        run: |
          npm ci # CI = Clean Install
          ls .
      - name: Comptage du nb de modules installés
        run: |
          nb=$(ls node_modules | wc -l)  #liste avec ls  et compte avec wc
          echo "Il y a bien $nb modules installés dans ./node_modules"